# Generated by Django 5.0.6 on 2024-07-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangohelp', '0002_members_joined_date_members_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
