# Generated by Django 5.0.6 on 2024-07-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangohelp', '0003_rename_members_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('enroll', models.IntegerField(null=True)),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
    ]
