# Generated by Django 5.0.6 on 2024-07-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangohelp', '0005_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='auth',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
